name: seguridad_vial_app
description: App mÃ³vil para captura de hechos y monitoreo de patrullas
publish_to: 'none'
version: 1.10.8+47

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_local_notifications: ^17.2.2
  cupertino_icons: ^1.0.8

  http: ^1.2.2
  shared_preferences: ^2.2.2

  image_picker: ^1.1.2
  path_provider: ^2.1.4
  path: ^1.9.0
  open_filex: ^4.6.0
  file_saver: ^0.2.14
  share_plus: ^10.0.2
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.0

  fl_chart: ^0.66.2

  geolocator: ^11.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1

  flutter_foreground_task: ^6.1.3

  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/car.png
    - assets/images/guardiacivil.png
    - assets/images/guardiacivilcon.png

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/guardiacivilcon.png
  remove_alpha_ios: true
